name: Publish

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: plugin-files/

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    needs: build

    environment:
      name: github-pages

    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v1
